# Generated by Django 3.2.8 on 2021-12-10 11:15

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=markdownx.models.MarkdownxField(verbose_name='テキスト'),
        ),
    ]
